# Changes here will be overwritten by Copier
_commit: v5.0.2
_src_path: https://github.com/eccenca/cmem-plugin-template.git
author_mail: thomas.wilmering@eccenca.com
author_name: Thomas Wilmering
github_page: https://github.com/eccenca/cmem-plugin-csvcombine/
project_description: This eccenca Corporate Memory plugin totally rocks :-)
project_slug: csvcombine
pypi: false

