# Changes here will be overwritten by Copier
_commit: v7.1.0
_src_path: https://github.com/eccenca/cmem-plugin-template.git
author_mail: cmempy-developer@eccenca.com
author_name: eccenca GmbH
github_page: https://github.com/eccenca/cmem-plugin-csvcombine/
project_description: Combine CSV files with the same structure to one dataset.
project_slug: csvcombine
project_type: plugin
pypi: true

